import { useState, useCallback } from 'react';
import { executeAction } from '../../stores/actionStore';
import { findTemplate, hasTemplate } from '../../utils/actionTemplates';
import { useAppData } from '../../context/AppDataContext';
import DynamicActionForm from './DynamicActionForm';

export interface ActionItem {
  id: string;
  text: string;
  priority: 'high' | 'medium' | 'low';
  category: 'portfolio' | 'budget' | 'tax' | 'insurance' | 'general';
  completed: boolean;
  completedDate?: string;
  completedNote?: string;
  // What should update when this is completed
  onComplete?: {
    type: 'move_cash' | 'update_holding' | 'update_budget' | 'info_only';
    description: string;
    fields?: { label: string; key: string; type: 'number' | 'text' | 'select'; options?: string[] }[];
  };
}


// Empty by design: per-user action items are generated by utils/dynamicActions.ts
// from real profile + account data. Seeding the store with hardcoded $-amount items
// (BofA savings, ISO exercises, Mimecast rollovers, etc.) leaked one user's data
// into every fresh install — those have been removed.
export const defaultActionItems: ActionItem[] = [];


interface ActionItemsProps {
  items: ActionItem[];
  onItemsChange: (items: ActionItem[]) => void;
  filter?: 'all' | 'portfolio' | 'budget' | 'tax' | 'insurance';
}

export default function ActionItemsView({ items, onItemsChange, filter = 'all' }: ActionItemsProps) {
  const { accounts } = useAppData();
  const [expandedId, setExpandedId] = useState<string | null>(null);
  const [completionData, setCompletionData] = useState<Record<string, string>>({});
  const [showCompleted, setShowCompleted] = useState(false);

  const filtered = items.filter(i => filter === 'all' || i.category === filter);
  const pending = filtered.filter(i => !i.completed);
  const completed = filtered.filter(i => i.completed);

  const [executing, setExecuting] = useState(false);
  const [resultMessage, setResultMessage] = useState<string | null>(null);

  const handleComplete = useCallback(async (id: string) => {
    setExecuting(true);
    setResultMessage(null);

    try {
      // Execute the action — this modifies portfolio/budget data
      const result = await executeAction(id, completionData);

      if (!result.success) {
        setResultMessage(result.message);
        setExecuting(false);
        return;
      }

      // Mark item complete
      let updated = items.map(i => {
        if (i.id === id) {
          return { ...i, completed: true, completedDate: new Date().toISOString().split('T')[0], completedNote: JSON.stringify(completionData) };
        }
        return i;
      });

      // Add any new action items generated by the completion
      if (result.newActionItems) {
        for (const newItem of result.newActionItems) {
          updated.push({
            id: newItem.id || `generated-${Date.now()}`,
            text: newItem.text || '',
            priority: (newItem.priority as 'high' | 'medium' | 'low') || 'low',
            category: (newItem.category as 'portfolio' | 'budget' | 'tax' | 'insurance' | 'general') || 'general',
            completed: false,
          });
        }
      }

      onItemsChange(updated);
      setResultMessage(result.message);
      setTimeout(() => { setExpandedId(null); setCompletionData({}); setResultMessage(null); }, 3000);
    } catch (err: any) {
      setResultMessage(`Error: ${err.message}`);
    }
    setExecuting(false);
  }, [items, completionData, onItemsChange]);

  const handleUndo = useCallback((id: string) => {
    const updated = items.map(i => i.id === id ? { ...i, completed: false, completedDate: undefined, completedNote: undefined } : i);
    onItemsChange(updated);
  }, [items, onItemsChange]);

  return (
    <div className="space-y-3">
      {/* Pending Items */}
      {pending.sort((a, b) => {
        const p = { high: 0, medium: 1, low: 2 };
        return p[a.priority] - p[b.priority];
      }).map(item => (
        <div key={item.id} className={`rounded-xl border transition-all ${
          item.priority === 'high' ? 'border-negative/20 bg-negative/5' :
          item.priority === 'medium' ? 'border-warning/20 bg-warning/5' :
          'border-glass-border bg-white/[0.02]'
        }`}>
          <div className="p-3 flex items-start gap-3 cursor-pointer" onClick={() => setExpandedId(expandedId === item.id ? null : item.id)}>
            <button onClick={e => { e.stopPropagation(); setExpandedId(item.id); }}
              className="w-5 h-5 mt-0.5 rounded border-2 border-text-muted/30 flex-shrink-0 hover:border-accent transition-colors" />
            <div className="flex-1">
              <div className="flex items-center gap-2">
                <span className={`text-[10px] uppercase tracking-wider font-bold px-1.5 py-0.5 rounded ${
                  item.priority === 'high' ? 'bg-negative/15 text-negative' :
                  item.priority === 'medium' ? 'bg-warning/15 text-warning' :
                  'bg-white/10 text-text-muted'
                }`}>{item.priority}</span>
                <span className="text-[10px] uppercase tracking-wider text-text-muted">{item.category}</span>
              </div>
              <p className="text-sm text-text-secondary mt-1">{item.text}</p>
            </div>
          </div>

          {/* Expanded completion form */}
          {expandedId === item.id && (item.onComplete || hasTemplate(item.id)) && (
            <div className="px-3 pb-3 pt-1 border-t border-glass-border space-y-3">
              {hasTemplate(item.id) ? (
                <>
                  <p className="text-xs text-text-muted">
                    {findTemplate(item.id)?.detail || item.onComplete?.description}
                  </p>
                  {(findTemplate(item.id)?.inputs?.length ?? 0) > 0 && (
                    <DynamicActionForm
                      template={findTemplate(item.id)!}
                      value={completionData}
                      onChange={setCompletionData}
                      accounts={accounts}
                    />
                  )}
                </>
              ) : (
                <>
                  <p className="text-xs text-text-muted">{item.onComplete?.description}</p>
                  {item.onComplete?.fields && item.onComplete.fields.length > 0 && (
                    <div className="grid grid-cols-2 gap-3">
                      {item.onComplete.fields.map(f => (
                        <div key={f.key}>
                          <label className="text-xs text-text-muted mb-1 block">{f.label}</label>
                          <input
                            type={f.type === 'number' ? 'number' : 'text'}
                            value={completionData[f.key] || ''}
                            onChange={e => setCompletionData(d => ({ ...d, [f.key]: e.target.value }))}
                            className="w-full bg-surface-2 border border-glass-border rounded-lg px-3 py-1.5 text-sm text-text-primary outline-none focus:border-accent/50"
                            placeholder={f.label}
                          />
                        </div>
                      ))}
                    </div>
                  )}
                </>
              )}
              {resultMessage && (
                <div className={`text-xs p-2 rounded-lg ${resultMessage.startsWith('Error') ? 'bg-negative/10 text-negative' : 'bg-positive/10 text-positive'}`}>
                  {resultMessage}
                </div>
              )}
              <div className="flex gap-2">
                <button onClick={() => handleComplete(item.id)} disabled={executing}
                  className="px-4 py-1.5 bg-positive hover:bg-positive/80 rounded-lg text-sm font-medium text-white transition-colors disabled:opacity-50">
                  {executing ? '⏳ Applying...' : '✓ Complete & Apply Changes'}
                </button>
                <button onClick={() => { setExpandedId(null); setResultMessage(null); }}
                  className="px-4 py-1.5 bg-surface-3 hover:bg-surface-4 rounded-lg text-sm text-text-secondary transition-colors">
                  Cancel
                </button>
              </div>
            </div>
          )}
        </div>
      ))}

      {/* Completed Items */}
      {completed.length > 0 && (
        <div>
          <button onClick={() => setShowCompleted(!showCompleted)}
            className="text-xs text-text-muted hover:text-text-secondary transition-colors">
            {showCompleted ? '▼' : '▶'} {completed.length} knocked out
          </button>
          {showCompleted && completed.map(item => (
            <div key={item.id} className="mt-2 p-3 rounded-xl bg-positive/5 border border-positive/10 flex items-center gap-3">
              <div className="w-5 h-5 rounded bg-positive/20 flex items-center justify-center text-positive text-xs">✓</div>
              <div className="flex-1">
                <p className="text-sm text-text-muted line-through">{item.text}</p>
                <p className="text-xs text-text-muted mt-0.5">Completed {item.completedDate}</p>
              </div>
              <button onClick={() => handleUndo(item.id)} className="text-xs text-text-muted hover:text-text-secondary">Undo</button>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
